### ISSUE TITLE
[ Blockate/BlockBot ] doesnt work when executing

### ISSUE THREAD

**Issue by caracalboomerang** [choke-dev/scripts#5]
doesnt give an error it just doesnt work

executor delta

**Comment by caracalboomerang** [comment]
i have also changed the bot name

**Comment by choke-dev** [comment]
Either this issue is from the executor you are using or i broke something.

I just recently updated the commands and main file so try that

**Comment by choke-dev** [comment]
@caracalboomerang, i have identified the issue, should be fixed

If the script is still not working please use [Fluxus Android](https://fluxteam.net/android/)
